{
 "title": "Loki + Alloy Syslog",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "logs", "query": "loki" },
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "host",
    "query": {}
   },
   {
    "name": "app",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "gloabl log rate by appname",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\"}[1m])) by (app)",
     "legendFormat": "{{appname}}"
    }
   ]
  },
  {
   "title": "Global Average Log Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "logs/min" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global Average Log Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(bytes_over_time({job=\"syslog\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Host Average Log Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "logs/min" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\",host=\"$host\"}[1m]))"
    }
   ]
  },
  {
   "title": "Host Log Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(bytes_over_time({job=\"syslog\",host=\"$host\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Appname Log Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(bytes_over_time({job=\"syslog\",app=\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Appname Average Log Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "logs/min" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\",app=\"$app\"}[1m]))"
    }
   ]
  },
  {
   "title": "Filtered Log Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(bytes_over_time({job=\"syslog\",host=\"$host\",app=\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Filtered Average Log Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "logs/min" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"syslog\",host=\"$host\",app=\"$app\"}[1m]))"
    }
   ]
  },
  {
   "title": "local log rate by appname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({host=\"$host\",job=\"syslog\"}[1m])) by (app)",
     "legendFormat": "{{appname}}"
    }
   ]
  },
  {
   "title": "local log count by appname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "global log count by appname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "filtered syslog",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"syslog\",host=\"$host\",app=\"$app\"}"
    }
   ]
  }
 ]
}